In [29]:
from collections import Counter, namedtuple
from IPython.display import clear_output, display
from tqdm import tqdm_notebook as tqdm
from util import (
    calculate_score,
    feature_to_target,
    load_data,
    target_to_feature,
)

import numpy as np
import matplotlib.pyplot as plt
import ipywidgets as widgets
import pandas as pd
import scipy.stats as sps

%matplotlib inline
%load_ext autoreload
%autoreload 2

TRAIN_FILE = './data/train_clean.csv'
TEST_FILE = './data/test_clean.csv'
RANDOM_STATE = 42

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [2]:
train_df, test_df = load_data(TRAIN_FILE, TEST_FILE, None, None)
train_df.head()

,id,epoch,sat_id,x,y,z,Vx,Vy,Vz,x_sim,y_sim,z_sim,Vx_sim,Vy_sim,Vz_sim
0,0,2014-01-01 00:00:00.000,0,-8855.823863,13117.780146,-20728.353233,-0.908303,-3.808436,-2.022083,-8843.131454,13138.221690,-20741.615306,-0.907527,-3.804930,-2.024133
1,1,2014-01-01 00:46:43.000,0,-10567.672384,1619.746066,-24451.813271,-0.302590,-4.272617,-0.612796,-10555.500066,1649.289367,-24473.089556,-0.303704,-4.269816,-0.616468
2,2,2014-01-01 01:33:26.001,0,-10578.684043,-10180.467460,-24238.280949,0.277435,-4.047522,0.723155,-10571.858472,-10145.939908,-24271.169776,0.274880,-4.046788,0.718768
3,3,2014-01-01 02:20:09.001,0,-9148.251857,-20651.437460,-20720.381279,0.715600,-3.373762,1.722115,-9149.620794,-20618.200201,-20765.019094,0.712437,-3.375202,1.718306
4,4,2014-01-01 03:06:52.002,0,-6719.092336,-28929.061629,-14938.907967,0.992507,-2.519732,2.344703,-6729.358857,-28902.271436,-14992.399986,0.989382,-2.522618,2.342237

In [35]:
SAT_ID = 0
VAR = 'x'
MAX_SAT_ID = np.max(train_df.sat_id.values)

def on_next_satellite(b):
    global SAT_ID, MAX_SAT_ID, VAR
    sat_data = train_df[train_df.sat_id == SAT_ID]
    with output:
        clear_output(wait=True)
        print(f'sat = {SAT_ID}, var = {VAR}')
        plt.plot(sat_data[VAR].values - sat_data[target_to_feature(VAR)].values)
        plt.show()
        SAT_ID += 1

def on_prev_satellite(b):
    global SAT_ID, MAX_SAT_ID, VAR
    sat_data = train_df[train_df.sat_id == SAT_ID]
    with output:
        clear_output(wait=True)
        print(f'sat = {SAT_ID}, var = {VAR}')
        plt.plot(sat_data[VAR].values - sat_data[target_to_feature(VAR)].values)
        plt.show()
        SAT_ID -= 1

In [36]:
button_prev = widgets.Button(description="Previous")
button_next = widgets.Button(description="Next")

button_prev.on_click(on_prev_satellite)
button_next.on_click(on_next_satellite)

output = widgets.Output()
display(button_prev, button_next, output)

Button(description='Previous', style=ButtonStyle())

Button(description='Next', style=ButtonStyle())

Output()

In [44]:
SAT_ID = 71
sat_df = train_df[train_df.sat_id == SAT_ID]
xs = sat_df.x.values
ids = np.argsort(xs)
ids_diff = np.abs(ids[1:] - ids[:-1])
sps.mode(ids_diff).mode[0], np.median(ids_diff)

(289, 385.0)

In [38]:
count = Counter()
sat_id_to_mode = dict()
for sat_id in set(train_df.sat_id):
    sat_df = train_df[train_df.sat_id == sat_id]
    xs = sat_df.x.values
    ids = np.argsort(xs)
    ids_diff = np.abs(ids[1:] - ids[:-1])
    mode = sps.mode(ids_diff).mode[0]
    count[mode] += 1
    sat_id_to_mode[sat_id] = mode

In [40]:
sat_id_to_mode

{0: 24,
 1: 24,
 2: 24,
 3: 24,
 4: 24,
 5: 1607,
 6: 24,
 7: 24,
 8: 24,
 9: 24,
 10: 24,
 11: 24,
 12: 24,
 13: 24,
 14: 24,
 15: 24,
 16: 24,
 17: 24,
 18: 24,
 19: 24,
 20: 50,
 21: 24,
 22: 24,
 23: 24,
 24: 24,
 25: 24,
 26: 24,
 27: 24,
 28: 24,
 29: 24,
 30: 24,
 31: 24,
 32: 24,
 33: 24,
 34: 24,
 35: 24,
 36: 24,
 37: 24,
 38: 24,
 39: 24,
 40: 24,
 41: 24,
 42: 24,
 43: 24,
 44: 24,
 45: 24,
 46: 24,
 47: 24,
 48: 24,
 49: 24,
 50: 24,
 51: 24,
 52: 24,
 53: 24,
 54: 24,
 55: 24,
 56: 24,
 57: 24,
 58: 24,
 59: 24,
 60: 24,
 61: 24,
 62: 24,
 63: 24,
 64: 24,
 65: 24,
 66: 24,
 67: 24,
 68: 24,
 69: 24,
 70: 24,
 71: 289,
 72: 24,
 73: 24,
 74: 24,
 75: 24,
 76: 24,
 77: 24,
 78: 24,
 79: 24,
 80: 359,
 81: 24,
 82: 24,
 83: 24,
 84: 24,
 85: 24,
 86: 24,
 87: 24,
 88: 24,
 89: 24,
 90: 24,
 91: 24,
 92: 24,
 93: 24,
 94: 24,
 95: 24,
 96: 24,
 97: 24,
 98: 24,
 99: 24,
 100: 24,
 101: 24,
 102: 24,
 103: 24,
 104: 24,
 105: 24,
 106: 24,
 107: 24,
 108: 24,
 109: 24,
 110: 24,
 111: 24,
 112: 24,
 113: 24,
 114: 24,
 115: 24,
 116: 24,
 117: 24,
 118: 24,
 119: 24,
 120: 24,
 121: 24,
 122: 24,
 123: 24,
 124: 24,
 125: 24,
 126: 24,
 127: 335,
 128: 24,
 129: 24,
 130: 24,
 131: 24,
 132: 24,
 133: 24,
 134: 24,
 135: 24,
 136: 815,
 137: 24,
 138: 24,
 139: 24,
 140: 74,
 141: 24,
 142: 24,
 143: 24,
 144: 24,
 145: 24,
 146: 24,
 147: 24,
 148: 24,
 149: 24,
 150: 24,
 151: 24,
 152: 24,
 153: 24,
 154: 24,
 155: 24,
 156: 1247,
 157: 24,
 158: 24,
 159: 479,
 160: 24,
 161: 24,
 162: 24,
 163: 24,
 164: 24,
 165: 24,
 166: 1248,
 167: 24,
 168: 24,
 169: 24,
 170: 24,
 171: 24,
 172: 24,
 173: 24,
 174: 24,
 175: 24,
 176: 24,
 177: 24,
 178: 24,
 179: 24,
 180: 24,
 181: 24,
 182: 24,
 183: 24,
 184: 1512,
 185: 24,
 186: 24,
 187: 24,
 188: 24,
 189: 24,
 190: 24,
 191: 24,
 192: 24,
 193: 24,
 194: 24,
 195: 24,
 196: 24,
 197: 24,
 198: 24,
 199: 24,
 200: 24,
 201: 24,
 202: 24,
 203: 24,
 204: 24,
 205: 24,
 206: 2256,
 207: 24,
 208: 24,
 209: 527,
 210: 24,
 211: 24,
 212: 937,
 213: 24,
 214: 24,
 215: 24,
 216: 24,
 217: 24,
 218: 24,
 219: 24,
 220: 24,
 221: 24,
 222: 24,
 223: 24,
 224: 72,
 225: 24,
 226: 841,
 227: 24,
 228: 48,
 229: 24,
 230: 24,
 231: 695,
 232: 1223,
 233: 24,
 234: 1007,
 235: 24,
 236: 24,
 237: 24,
 238: 24,
 239: 24,
 240: 24,
 241: 24,
 242: 24,
 243: 24,
 244: 24,
 245: 24,
 246: 24,
 247: 24,
 248: 24,
 249: 74,
 250: 24,
 251: 24,
 252: 24,
 253: 24,
 254: 24,
 255: 552,
 256: 24,
 257: 24,
 258: 24,
 259: 24,
 260: 24,
 261: 24,
 262: 24,
 263: 24,
 264: 49,
 265: 24,
 266: 24,
 267: 24,
 268: 24,
 269: 24,
 270: 24,
 271: 73,
 272: 24,
 273: 455,
 274: 24,
 275: 24,
 276: 24,
 277: 23,
 278: 24,
 279: 24,
 280: 24,
 281: 24,
 282: 24,
 283: 24,
 284: 1679,
 285: 24,
 286: 24,
 287: 1007,
 288: 24,
 289: 24,
 290: 24,
 291: 769,
 292: 24,
 293: 24,
 294: 24,
 295: 24,
 296: 431,
 297: 24,
 298: 24,
 299: 24,
 300: 24,
 301: 24,
 302: 24,
 303: 24,
 304: 24,
 305: 24,
 306: 24,
 307: 1535,
 308: 24,
 309: 24,
 310: 1,
 311: 647,
 312: 1343,
 313: 24,
 314: 24,
 315: 24,
 316: 24,
 317: 24,
 318: 24,
 319: 24,
 320: 24,
 321: 503,
 322: 24,
 323: 791,
 324: 24,
 325: 24,
 326: 24,
 327: 24,
 328: 24,
 329: 24,
 330: 24,
 331: 24,
 332: 24,
 333: 24,
 334: 24,
 335: 24,
 336: 24,
 337: 24,
 338: 24,
 339: 24,
 340: 24,
 341: 24,
 342: 24,
 343: 24,
 344: 24,
 345: 24,
 346: 24,
 347: 24,
 348: 24,
 349: 24,
 350: 24,
 351: 24,
 352: 24,
 353: 24,
 354: 24,
 355: 24,
 356: 24,
 357: 24,
 358: 24,
 359: 24,
 360: 24,
 361: 24,
 362: 24,
 363: 24,
 364: 24,
 365: 24,
 366: 24,
 367: 24,
 368: 24,
 369: 24,
 370: 24,
 371: 24,
 372: 24,
 373: 24,
 374: 24,
 375: 24,
 376: 24,
 377: 24,
 378: 24,
 379: 24,
 380: 24,
 381: 24,
 382: 24,
 383: 24,
 384: 24,
 385: 24,
 386: 1247,
 387: 24,
 388: 24,
 389: 24,
 390: 24,
 391: 49,
 392: 24,
 393: 24,
 394: 24,
 395: 24,
 396: 24,
 397: 24,
 398: 24,
 399: 24,
 400: 24,
 401: 24,
 402: 49,
 403: 24,
 404: 24,
 405: 24,
 406: 24,
 407: 24,
 408: 24,
 409: 24,
 410: 24,
 411: 24,
 412: 24,
 413: 24,
 414: 24,
 415: 24,
 416: 24,
 417: 24,
 418: 24,
 419: 24,
 420: 24,
 421: 24,
 422: 24,
 423: 24,
 424: 24,
 425: 24,
 426: 24,
 427: 24,
 428: 24,
 429: 385,
 430: 24,
 431: 24,
 432: 24,
 433: 24,
 434: 24,
 435: 24,
 436: 24,
 437: 24,
 438: 72,
 439: 24,
 440: 24,
 441: 24,
 442: 123,
 443: 24,
 444: 24,
 445: 24,
 446: 24,
 447: 24,
 448: 24,
 449: 24,
 450: 24,
 451: 24,
 452: 24,
 453: 24,
 454: 24,
 455: 24,
 456: 24,
 457: 24,
 458: 1343,
 459: 24,
 460: 24,
 461: 1152,
 462: 24,
 463: 24,
 464: 24,
 465: 24,
 466: 24,
 467: 24,
 468: 24,
 469: 24,
 470: 24,
 471: 24,
 472: 24,
 473: 24,
 474: 24,
 475: 24,
 476: 1898,
 477: 24,
 478: 24,
 479: 24,
 480: 24,
 481: 24,
 482: 600,
 483: 24,
 484: 24,
 485: 24,
 486: 24,
 487: 25,
 488: 24,
 489: 24,
 490: 24,
 491: 1896,
 492: 24,
 493: 24,
 494: 24,
 495: 24,
 496: 24,
 497: 24,
 498: 24,
 499: 24,
 500: 24,
 501: 24,
 502: 24,
 503: 24,
 504: 25,
 505: 24,
 506: 24,
 507: 24,
 508: 24,
 509: 24,
 510: 24,
 511: 24,
 512: 24,
 513: 24,
 514: 71,
 515: 1,
 516: 24,
 517: 24,
 518: 480,
 519: 24,
 520: 24,
 521: 24,
 522: 24,
 523: 24,
 524: 25,
 525: 24,
 526: 1559,
 527: 1418,
 528: 24,
 529: 24,
 530: 24,
 531: 24,
 532: 24,
 533: 24,
 534: 24,
 535: 24,
 536: 24,
 537: 24,
 538: 24,
 539: 24,
 540: 24,
 541: 24,
 542: 24,
 543: 24,
 544: 24,
 545: 24,
 546: 24,
 547: 24,
 548: 24,
 549: 24,
 550: 24,
 551: 24,
 552: 24,
 553: 24,
 554: 24,
 555: 647,
 556: 24,
 557: 24,
 558: 24,
 559: 24,
 560: 24,
 561: 24,
 562: 24,
 563: 24,
 564: 24,
 565: 24,
 566: 24,
 567: 24,
 568: 24,
 569: 24,
 570: 24,
 571: 24,
 572: 24,
 573: 24,
 574: 361,
 575: 24,
 576: 24,
 577: 24,
 578: 24,
 579: 24,
 580: 24,
 581: 24,
 582: 24,
 583: 24,
 584: 24,
 585: 24,
 586: 407,
 587: 24,
 588: 1035,
 589: 24,
 590: 24,
 591: 24,
 592: 24,
 593: 24,
 594: 24,
 595: 24,
 596: 24,
 597: 24,
 598: 24,
 599: 24}

In [37]:
count

Counter({24: 541,
         1607: 1,
         50: 1,
         289: 1,
         359: 1,
         335: 1,
         815: 1,
         74: 2,
         1247: 2,
         479: 1,
         1248: 1,
         1512: 1,
         2256: 1,
         527: 1,
         937: 1,
         72: 2,
         841: 1,
         48: 1,
         695: 1,
         1223: 1,
         1007: 2,
         552: 1,
         49: 3,
         73: 1,
         455: 1,
         23: 1,
         1679: 1,
         769: 1,
         431: 1,
         1535: 1,
         1: 2,
         647: 2,
         1343: 2,
         503: 1,
         791: 1,
         385: 1,
         123: 1,
         1152: 1,
         1898: 1,
         600: 1,
         25: 3,
         1896: 1,
         71: 1,
         480: 1,
         1559: 1,
         1418: 1,
         361: 1,
         407: 1,
         1035: 1})